// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SppProtocol.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Request_WifiInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Request_RequestType

typedef GPB_ENUM(Request_RequestType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Request_RequestType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Request_RequestType_Alexa = 0,
  Request_RequestType_Spotify = 1,
  Request_RequestType_Soundcolud = 2,
  Request_RequestType_Mediacontrol = 3,
  Request_RequestType_Wifi = 4,
};

GPBEnumDescriptor *Request_RequestType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Request_RequestType_IsValidValue(int32_t value);

#pragma mark - Enum Request_MediaCommand

typedef GPB_ENUM(Request_MediaCommand) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Request_MediaCommand_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Request_MediaCommand_Play = 0,
  Request_MediaCommand_Pause = 1,
  Request_MediaCommand_Next = 2,
  Request_MediaCommand_Pre = 3,
  Request_MediaCommand_Collecton = 4,
  Request_MediaCommand_Volup = 5,
  Request_MediaCommand_Voldowm = 6,
};

GPBEnumDescriptor *Request_MediaCommand_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Request_MediaCommand_IsValidValue(int32_t value);

#pragma mark - Enum Response_ResponseCode

typedef GPB_ENUM(Response_ResponseCode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Response_ResponseCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Response_ResponseCode_Success = 0,
  Response_ResponseCode_Fail = 1,
};

GPBEnumDescriptor *Response_ResponseCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Response_ResponseCode_IsValidValue(int32_t value);

#pragma mark - SppProtocolRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SppProtocolRoot : GPBRootObject
@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_Type = 1,
  Request_FieldNumber_Code = 2,
  Request_FieldNumber_Control = 3,
  Request_FieldNumber_WifiInfo = 4,
  Request_FieldNumber_MediaCmd = 5,
};

typedef GPB_ENUM(Request_Content_OneOfCase) {
  Request_Content_OneOfCase_GPBUnsetOneOfCase = 0,
  Request_Content_OneOfCase_Code = 2,
  Request_Content_OneOfCase_Control = 3,
  Request_Content_OneOfCase_WifiInfo = 4,
  Request_Content_OneOfCase_MediaCmd = 5,
};

@interface Request : GPBMessage

@property(nonatomic, readwrite) Request_RequestType type;

@property(nonatomic, readonly) Request_Content_OneOfCase contentOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@property(nonatomic, readwrite) int32_t control;

@property(nonatomic, readwrite, strong, null_resettable) Request_WifiInfo *wifiInfo;

@property(nonatomic, readwrite) Request_MediaCommand mediaCmd;

@end

/**
 * Fetches the raw value of a @c Request's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Request_Type_RawValue(Request *message);
/**
 * Sets the raw value of an @c Request's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequest_Type_RawValue(Request *message, int32_t value);

/**
 * Fetches the raw value of a @c Request's @c mediaCmd property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Request_MediaCmd_RawValue(Request *message);
/**
 * Sets the raw value of an @c Request's @c mediaCmd property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequest_MediaCmd_RawValue(Request *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'content'.
 **/
void Request_ClearContentOneOfCase(Request *message);

#pragma mark - Request_WifiInfo

typedef GPB_ENUM(Request_WifiInfo_FieldNumber) {
  Request_WifiInfo_FieldNumber_Ssid = 1,
  Request_WifiInfo_FieldNumber_Pwd = 2,
};

@interface Request_WifiInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ssid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pwd;

@end

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_Code = 1,
  Response_FieldNumber_Reason = 2,
};

@interface Response : GPBMessage

@property(nonatomic, readwrite) Response_ResponseCode code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

/**
 * Fetches the raw value of a @c Response's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Response_Code_RawValue(Response *message);
/**
 * Sets the raw value of an @c Response's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponse_Code_RawValue(Response *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
